name: nerffaceshop
channels:
  - pytorch
  - nvidia
dependencies:
  - python
  - pip
  - numpy>=1.20
  - click>=8.0
  - pillow
  - scipy=1.7.1
  - pytorch==2.5.1
  - torchvision==0.20.1
  - pytorch-cuda=12.4
  - requests=2.26.0
  - tqdm=4.62.2
  - ninja=1.10.2
  - matplotlib=3.4.2
  - imageio=2.9.0
  - pip:
    - imgui==1.3.0
    - glfw==2.2.0
    - pyopengl==3.1.5
    - imageio-ffmpeg==0.4.3
    - pyspng
    - psutil
    - mrcfile
    - tensorboard
    - mediapipe
    - dlib
    - hydra-core
    - smplx
    - pytorch_toolbelt
    - coloredlogs
    - chumpy
    - scikit-image
    - git+https://github.com/facebookresearch/pytorch3d.git@stable
    - face_alignment
    - yacs
    - kornia
    - torchmetrics
    - lpips
    - torchfields
    - einops